---
- name: "Install SonarQube on a RedHat/CentOS/Fedora Host"
  become: True
  hosts: "{{ nodes | default('tools') }}"  #Because I have a node called tools
  tasks:
    - name: "Put SELinux in permissive mode" #Not a good practice
      selinux:
        policy: targeted
        state: permissive

    - name: "Increase vm.max_map_count kernel file descriptior"
      ansible.builtin.blockinfile:
        path: /etc/security/limits.conf
        block: |
          sonarqube     -   nofile       65536"
          sonarqube     -   nproc        4096"
    
    - name: "Create sonarqube user"
      ansible.builtin.user:
        name: sonar
        password: sonar

    - name: "Install Java on Centos 8"
      yum:
        name: java-11-openjdk-devel
        state: present

    - name: "Update system"
      yum:
        name: '*'
        state: latest
        exclude: kernel*

    - name: "Install PostgreSQL 14 Repository For SonarQube"
      ansible.builtin.yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        disable_gpg_check: true
        state: present

    - name: "Disable postgres module"
      command: dnf -qy module disable postgresql
       
    - name: "Install PostgreSQL 14"
      yum:
        name:
          - postgresql14
          - postgresql14-server
        state: present

    - name: "Check to see if the database has already been initialized"
      stat:
        path: /var/lib/pgsql/14/data/
      register: file_check
  
    - name: "Initialize the Postgres database"
      command: /usr/pgsql-14/bin/postgresql-14-setup initdb
      ignore_errors: yes
      when: not file_check.stat.exists

    - name: "Start and enable PostgreSQL 14"
      service:
        name: postgresql-14
        enabled: true
        state: started